name: Desktop Release (Test)

on:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: mkdir dist
      - run: echo Foo >> dist/foo.txt
      - run: ls

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: assets
          path: 'packages/desktop/dist/*+(.txt|.exe)'

