name: Desktop Release (Test)

on:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build:web:all

      - name: Compile for AppImage
        run: yarn run webpack --config desktop.webpack.prod.js
      - name: AppImage
        run: yarn run electron-builder --linux --x64 --ia32 -c.linux.target=AppImage --publish=never

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: assets
          path: 'packages/desktop/dist/'

  Publish:
    runs-on: ubuntu-latest
    needs: [Linux]
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: assets
          path: packages/desktop/dist
      - run: node scripts/sums.mjs
      - run: node scripts/create-draft-release.mjs
