name: Desktop Release (Test)

on:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build:web:all

      - name: Install Snap Deps
        run: |
          sudo snap install snapcraft --classic
      - name: SnapArm64
        run: |
          yarn run webpack --config desktop.webpack.prod.js --env snap
          yarn run electron-builder --linux --arm64 -c.linux.target=snap --publish=never
        env:
          npm_config_target_arch: 'arm64'
          SNAPCRAFT_BUILD_ENVIRONMENT: 'managed-host'

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: assets
          path: |
            packages/desktop/dist/*.snap
            packages/desktop/dist/*.AppImage
            packages/desktop/dist/*.deb
            packages/desktop/dist/*.blockmap
            packages/desktop/dist/*.yml
            packages/desktop/dist/*.yaml
