name: Desktop Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/desktop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build


  Linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Compile for AppImage
        run: yarn run webpack --config desktop.webpack.prod.js
      - name: AppImage
        run: yarn run electron-builder --linux --x64 --ia32 -c.linux.target=AppImage --publish=never

      - name: Snap
        run: yarn run webpack --config desktop.webpack.prod.js --env snap'
        run: yarn run electron-builder --linux --x64 -c.linux.target=snap --publish=never

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: assets
          path: 'dist/'

  Publish:
    runs-on: ubuntu-latest
    needs: [Linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: assets
          path: dist
      - run: node scripts/sums.mjs
      - run: node scripts/create-draft-release.mjs
