name: Desktop Tags Matching Release

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    uses: standardnotes/app/.github/workflows/desktop.release.reuse.yml@develop
    secrets: inherit
    with:
      channel: beta