name: Desktop Beta Release

on:
  create:
    tags:
      - '**standardnotes/desktop+(*alpha*|*beta*)'
  workflow_dispatch:

jobs:
  Build:
    uses: standardnotes/app/.github/workflows/desktop.release.reuse.yml@develop
    secrets: inherit
    with:
      channel: beta