name: Desktop Prod Release

on:
  create:
    tags:
      - '**standardnotes/desktop!(*alpha*|*beta*)'
  workflow_dispatch:

jobs:
  Build:
    uses: standardnotes/app/.github/workflows/desktop.release.reuse.yml@main
    secrets: inherit
    with:
      channel: prod