name: Desktop Release (Test)

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: mkdir files
      - run: echo Foo >> files/foo.txt
      - run: echo Bar >> files/bar.txt
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/desktop
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          tag_name: "@standardnotes/desktop@${{ steps.package-version.outputs.current-version}}"
          prerelease: true
          draft: true
          files: |
            packages/desktop/files/*